[package]
name = "paradocs"
version = "0.1.0"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"

[dependencies]
html5ever = "0.25.1"
kuchiki = "0.8.0"
reqwest = "0.10.4"

[dev-dependencies]
tokio = { version = "0.2.13", features = ["macros"] }
